const cows=[
{id:1,img:'1(2).png'},{id:45,img:'45(1).png'},{id:158,img:'158.png'},{id:159,img:'159.png'},{id:285,img:'285.png'},{id:398,img:'398.png'},{id:452,img:'452.png'},{id:512,img:'512.png'},{id:547,img:'547.png'},{id:863,img:'863.png'},{id:865,img:'865.png'},{id:1161,img:'1161.png'},{id:1164,img:'1164.png'}];
const pos=[[34,57],[44,66],[55,54],[66,65],[30,76],[40,82],[50,73],[61,82],[72,75],[38,69],[48,62],[59,69],[69,56]];
let milk=1240,claimable=130,tick=42,connected=false;
const cowLayer=document.getElementById('cowLayer'),cards=document.getElementById('cowCards');
function render(){cowLayer.innerHTML='';cards.innerHTML='';cows.forEach((c,i)=>{const m=document.createElement('div');m.className='moo';m.style.left=pos[i][0]+'%';m.style.top=pos[i][1]+'%';m.innerHTML=`<span class="tag">#${c.id}</span><img class="portrait" src="${c.img}" alt="MooPunk #${c.id}">`;m.onclick=()=>showCow(c);cowLayer.appendChild(m);const card=document.createElement('article');card.className='pixel cow-card';card.innerHTML=`<img src="${c.img}" alt="MooPunk #${c.id}"><h3>MooPunk #${c.id}</h3><div class="meta"><span>DAILY</span><b>10 MILK</b></div><div class="meta"><span>STATUS</span><b>ON FARM</b></div>`;card.onclick=()=>showCow(c);cards.appendChild(card)});document.getElementById('cowCount').textContent=cows.length}
function showCow(c){document.getElementById('modalImg').src=c.img;document.getElementById('modalTitle').textContent=`MooPunk #${c.id}`;document.getElementById('modal').classList.add('show')}
document.getElementById('close').onclick=()=>document.getElementById('modal').classList.remove('show');document.getElementById('modal').onclick=e=>{if(e.target.id==='modal')e.currentTarget.classList.remove('show')};
function update(){document.getElementById('milkBalance').textContent=milk.toLocaleString();document.getElementById('claimable').textContent=claimable.toLocaleString()}
document.getElementById('collect').onclick=()=>{if(!claimable)return;const amt=claimable;milk+=amt;claimable=0;update();const b=document.getElementById('milkBurst');b.textContent=`+${amt} MILK`;b.classList.remove('show');void b.offsetWidth;b.classList.add('show')};
document.querySelectorAll('.tab').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.querySelectorAll('.view').forEach(v=>v.classList.remove('active-view'));document.getElementById(btn.dataset.view).classList.add('active-view')});
document.getElementById('wallet').onclick=e=>{connected=!connected;e.currentTarget.textContent=connected?'0xMOO...FARM':'CONNECT WALLET';e.currentTarget.style.background=connected?'#ffd13f':'#72de55'};
document.querySelectorAll('.shop-card button').forEach(b=>b.onclick=()=>{const cost=+b.dataset.cost;if(milk>=cost){milk-=cost;update();b.textContent='OWNED ✓';b.disabled=true;b.style.background='#72de55'}else{const old=b.textContent;b.textContent='NOT ENOUGH MILK';setTimeout(()=>b.textContent=old,900)}});
setInterval(()=>{tick--;if(tick<0){tick=59;claimable+=cows.length;update()}document.getElementById('timer').textContent=`Next milk tick in 00:${String(tick).padStart(2,'0')}`;document.getElementById('progress').style.width=((59-tick)/59*100)+'%'},1000);
setInterval(()=>document.querySelectorAll('.moo').forEach((m,i)=>{m.style.transform=`translate(${Math.round(Math.random()*14-7)}px,${Math.round(Math.random()*8-4)}px)`}),1700);
render();update();
