const cows=[
{id:1,img:'./1(2).png'},{id:45,img:'./45(1).png'},{id:158,img:'./158.png'},{id:159,img:'./159.png'},{id:285,img:'./285.png'},{id:398,img:'./398.png'},{id:452,img:'./452.png'},{id:512,img:'./512.png'},{id:547,img:'./547.png'},{id:863,img:'./863.png'},{id:865,img:'./865.png'},{id:1161,img:'./1161.png'},{id:1164,img:'./1164.png'}
];
const positions=[[33,57],[42,69],[54,55],[65,68],[29,76],[39,82],[49,74],[60,82],[71,76],[37,70],[47,62],[58,70],[68,57]];
let milk=1240,claimable=cows.length*10,tick=42,connected=false;
const $=id=>document.getElementById(id),cowLayer=$('cowLayer'),cowCards=$('cowCards');
function renderCows(){cowLayer.innerHTML='';cowCards.innerHTML='';cows.forEach((cow,i)=>{const el=document.createElement('div');el.className='moo';el.style.left=positions[i][0]+'%';el.style.top=positions[i][1]+'%';el.innerHTML=`<span class="moo-label">#${cow.id}</span><div class="portrait"><img src="${cow.img}" alt="MooPunk #${cow.id}"></div>`;el.onclick=()=>openCow(cow);cowLayer.appendChild(el);const card=document.createElement('article');card.className='panel cow-card';card.innerHTML=`<img src="${cow.img}" alt="MooPunk #${cow.id}"><h3>MooPunk #${cow.id}</h3><div class="cow-meta"><span>DAILY</span><b>10 MILK</b></div><div class="cow-meta"><span>STATUS</span><b>ON FARM</b></div>`;card.onclick=()=>openCow(cow);cowCards.appendChild(card)});$('cowCount').textContent=cows.length;$('farmRate').textContent=`${cows.length*10} MILK / DAY`}
function openCow(cow){$('modalImg').src=cow.img;$('modalTitle').textContent=`MooPunk #${cow.id}`;$('cowModal').classList.add('show');$('cowModal').setAttribute('aria-hidden','false')}
function closeCow(){$('cowModal').classList.remove('show');$('cowModal').setAttribute('aria-hidden','true')}
$('modalClose').onclick=closeCow;$('cowModal').onclick=e=>{if(e.target===$('cowModal'))closeCow()};
function updateBalances(){$('milkBalance').textContent=milk.toLocaleString();$('claimable').textContent=claimable.toLocaleString()}
function milkParticles(){document.querySelectorAll('.moo').forEach((cow,i)=>{setTimeout(()=>{const p=document.createElement('div');p.className='milk-particle';p.textContent='🥛';const r=cow.getBoundingClientRect(),stage=$('farmStage').getBoundingClientRect();p.style.left=(r.left-stage.left+r.width/2-8)+'px';p.style.top=(r.top-stage.top+5)+'px';$('farmStage').appendChild(p);setTimeout(()=>p.remove(),1000)},i*45)})}
$('collectBtn').onclick=()=>{if(claimable<=0)return;const amount=claimable;milk+=amount;claimable=0;updateBalances();milkParticles();const burst=$('milkBurst');burst.textContent=`+${amount} MILK`;burst.classList.remove('show');void burst.offsetWidth;burst.classList.add('show');$('collectBtn').textContent='MILK COLLECTED ✓';setTimeout(()=>$('collectBtn').textContent='COLLECT MILK',1100)};
document.querySelectorAll('.nav-btn').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.nav-btn').forEach(b=>b.classList.remove('active'));document.querySelectorAll('.view').forEach(v=>v.classList.remove('active-view'));btn.classList.add('active');$(btn.dataset.view).classList.add('active-view')});
$('walletBtn').onclick=()=>{connected=!connected;$('walletBtn').textContent=connected?'0xMOO...FARM':'CONNECT WALLET';$('walletBtn').style.background=connected?'#ffd33f':'#7ee25d'};
document.querySelectorAll('.shop-buy').forEach(btn=>btn.onclick=()=>{const cost=Number(btn.dataset.cost);if(milk>=cost){milk-=cost;updateBalances();btn.textContent='OWNED ✓';btn.disabled=true;btn.style.background='#7ee25d'}else{const old=btn.textContent;btn.textContent='NOT ENOUGH MILK';setTimeout(()=>btn.textContent=old,900)}});
setInterval(()=>{tick--;if(tick<0){tick=59;claimable+=cows.length;updateBalances()}$('timer').textContent=`NEXT MILK TICK IN 00:${String(tick).padStart(2,'0')}`;$('progressBar').style.width=`${((59-tick)/59)*100}%`},1000);
setInterval(()=>{document.querySelectorAll('.moo').forEach(cow=>{const x=Math.round(Math.random()*14-7),y=Math.round(Math.random()*8-4);cow.style.transform=`translate(${x}px,${y}px)`})},1800);
renderCows();updateBalances();
